import { Badge } from "@/components/ui/badge"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { FadeIn, StaggerContainer, StaggerItem } from "@/components/ui/fade-in"

const faqs = [
  {
    q: "What wind speed is required for the Avatar turbines to work effectively?",
    a: "The Avatar series has a cut-in wind speed of just 1.4 m/s. Rajasthan, particularly western districts like Jaisalmer, Barmer, Jodhpur, and Bikaner, has excellent average wind speeds of 5–8 m/s, making it highly suitable for wind energy generation. We conduct a site-specific wind assessment before every installation.",
  },
  {
    q: "What is the expected payback period for a wind turbine investment?",
    a: "Payback periods vary by system size and local wind conditions, but our commercial customers typically see full ROI within 2 to 4 years due to tax depreciation benefits. After that, the energy generated is essentially free for the remaining 20+ year lifespan of the turbine.",
  },
  {
    q: "Do I need government approvals or permissions to install a wind turbine?",
    a: "Requirements depend on system size and location. Small residential systems (under 10 kW) typically require minimal approvals. Larger systems may require a net-metering agreement with your DISCOM. Our team handles all regulatory paperwork and liaising with authorities as part of our end-to-end EPC service.",
  },
  {
    q: "Is my location in Rajasthan suitable for wind energy?",
    a: "Most parts of Rajasthan receive excellent wind resources. We use meteorological data and on-site anemometer readings to confirm suitability. A free preliminary assessment is available for all interested customers before any commitment.",
  },
  {
    q: "What maintenance is required for Avatar wind turbines?",
    a: "Because Avatar turbines use a gearless Axial Flux generator, they require minimal maintenance — typically an annual inspection. Our maintenance packages include periodic health checks, remote monitoring, and priority response. Most components are designed to last 20+ years.",
  },
  {
    q: "Can I connect the wind turbine to the grid and sell excess power?",
    a: "Yes! Grid-tie systems (Avatar-I On-Grid) are available. Under Rajasthan's net-metering policy, excess electricity generated by your turbine can be exported to the grid, and you receive credit on your electricity bill.",
  },
  {
    q: "How do I become a distributor or franchise partner for Oasis Energy?",
    a: "We welcome motivated entrepreneurs and businesses to join our distribution network across Rajasthan. Distributorships are available on a district or tehsil basis. Contact us via our Partners page to discuss the opportunity.",
  },
]

export function FAQSection() {
  return (
    <section className="py-24 bg-white container mx-auto px-4" id="faq">
      <div className="max-w-4xl mx-auto">
        <FadeIn className="text-center mb-16">
          <Badge
            variant="outline"
            className="mb-6 text-accent border-accent/30 bg-accent/5 font-semibold px-4 py-1.5"
          >
            Frequently Asked Questions
          </Badge>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-primary tracking-tight mb-6 font-heading">
            Your Questions, <span className="text-gradient-brand">Answered</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto leading-relaxed font-light">
            Everything you need to know about wind energy, our products, and how
            to get started with Oasis Energy.
          </p>
        </FadeIn>

        <StaggerContainer>
          <Accordion className="space-y-4">
            {faqs.map((faq, i) => (
              <StaggerItem key={i}>
                <AccordionItem
                  value={`faq-${i}`}
                  className="bg-slate-50 border border-gray-100 rounded-2xl px-6 md:px-8 data-[state=open]:border-accent/40 data-[state=open]:shadow-md transition-all duration-300"
                >
                  <AccordionTrigger className="text-left text-base md:text-lg font-semibold text-primary hover:text-accent hover:no-underline py-6">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-base text-muted-foreground leading-relaxed pb-6 font-light">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              </StaggerItem>
            ))}
          </Accordion>
        </StaggerContainer>

        <FadeIn className="text-center mt-12">
          <p className="text-lg text-muted-foreground">
            Have more questions?{" "}
            <a href="/contact" className="text-accent font-semibold hover:underline">
              Contact our technical team →
            </a>
          </p>
        </FadeIn>
      </div>
    </section>
  )
}
